name: TEST_ACCTIONS

on: 
  release:
    types: [published]

  #启动方式

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 20 * * 6
  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "工作流运行于：$(lsb_release -d)"
        sudo -E apt-get update
        sudo -E apt-get -y install aria2 curl wget
        sudo -E apt-get autoremove --purge
        sudo -E apt-get clean

    - name: New Floder | 新文件夹
      env:
        WORK_DIR: workdir
      run: |
        mkdir $WORK_DIR
        cd $WORK_DIR

    - name: Work Code | 工作代码
      working-directory: ./workdir
      env:
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      run: |
        curl -X GET 'http://www.pushplus.plus/send?token=${{ secrets.PUSHPLUS_TOKEN }}&title=OpenWrt%20Build%20R3G%20&content=%E4%B8%8B%E8%BD%BD%E9%93%BE%E6%8E%A5%3ATEST&template=html

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        # Artifact name
        name: test
        # A file, directory or wildcard pattern that describes what to upload
        path: workdir

