name: TEST_ACCTIONS

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  #schedule:
  #  - cron: 0 20 * * 6
  
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "工作流运行于：$(lsb_release -d)"
        wget https://pan.69cc.pro/Tools/FirPE-V1.8.1.exe

    - name: Clone source code | 克隆源代码
      env:
      OUT_NAME: test.zip
      IN_NAME: FirPE-V1.8.1.exe
      run: |
        zip $OUT_NAME $IN_NAME

